### PR TITLE
Redo printing

### PR DESCRIPTION
**Pull request by tthsqe12**
See point 27 in challenges.md to see just how bad the printing situation is in singular.

### CODE REVIEW

**Comment by rfourquet** [comment]
I'm currently reviewing, but if I'm not mistaken, there is a regression:
```julia
Sing> list(1, 2);
 ERROR: transpilation error: internal error in convert_elemexpr 11-17
Stacktrace:
 [1] convert_elemexpr(::SingularInterpreter.AstNode, ::SingularInterpreter.AstEnv, ::Bool) at [...]
[...]
```

**Comment by tthsqe12** [comment]
@rfourquet make sure all of your deps are built properly.

**Comment by rfourquet** [comment]
> make sure all of your deps are built properly.

Ouch, once again! this didn't seem to be needed for this PR, but my master was not up-to-date on my laptop... I now need to check why I can't build anymore.

Otherwise, the changes look after a first skim, even though I'm quite not familiar with the printing stuff. I barely looked at the code-generation stuff which I know even less.

**Comment by tthsqe12** [comment]
Ok. The main thing is that `list(1,2,3)` prints without the extra lines as
```
list[1]: 1
    [2]: 2
    [3]: 3
```
and matrices print without commas

**Comment by rfourquet** [comment]
Sorry, my non-important review-comments have not been sent on time, must have had a connection problem.

**Pull request merged**
